#!/bin/bash

# Script to run through the batch sizes (alters config file and runs the algorithm)


#Go to the head folder with a Makefile in it
cd ../../

#Declaring arrays of the parameters we want to test
#declare -a iterations=(16 32 64 128 256 384 448)
declare -a iterations=(10000)
declare -a examples=(32 256 1024)

for j in `seq 0 1 $[${#examples[@]}-1]`
        do
                #Set a new value for Learning rate variables
                varLearning='        numbItTrain       = '${examples[j]}';'

                #Change values in the config file
	        sed -i.bu '14 s|.*|'"$varLearning"'|' ./config/config.cfg

                #Iterate through hidden layers
                for i in `seq 0 1 $[${#iterations[@]}-1]`
                do
                        #Set the path to a new directory
                        saveDir="/local/data/public/am2442/seismic/output/tanh/${batch[k]}/${examples[j]}/${iterations[i]}"

                        #Create a new directory for output      
                        mkdir -p $saveDir

                        #Set a new value for the hidden layers output
                        varold='        numbEpoches             = '${iterations[i]}';'

                        #Change a save folder to a created directory
                        varoldSave='        saveFolder         ="'$saveDir'/";'

                        #Set new variables in the config file
	                sed -i.bu '11 s|.*|'"$varold"'|' ./config/config.cfg
	                sed -i.bu '4 s|.*|'"$varoldSave"'|' ./config/config.cfg

                        #Run the neural network with a new configuration file
	                make run
                done
done


