#!/bin/bash

# Script to run through the batch sizes (alters config file and runs the algorithm)


#Go to the head folder with a Makefile in it
cd ../../

#Declaring arrays of the parameters we want to test
#declare -a lambdaArray=(16 32 64 128 256 384 448)
#declare -a lambdaArray=(2 4 8 16 32 48 56)
declare -a lambdaArray=(0.0000001 0.000001 0.00001 0.00001 0.0001 0.001 0.01) #should be lambda
#declare -a learningRate=(0.001 0.01 0.1)
declare -a learningRate=(0.01 0.1)
#declare -a learningRate=(0.0001 0.001 0.01 0.1)
declare -a batch=(4 8 16 32 64 128)


#Iterate through batch array
for k in `seq 0 1 $[${#batch[@]}-1]`
do      
        #Set a new value for batch variable in config
        varbatch='        miniBatch          = '${batch[k]}';'

        #Change a batch variable in the config
        sed -i.bu '22 s|.*|'"$varbatch"'|' ./config/config.cfg


        #Iterate through learning rate array
        for j in `seq 0 1 $[${#learningRate[@]}-1]`
        do
                #Set a new value for Learning rate variables
                varLearning='        learningRate       = '${learningRate[j]}';'
                varLearningRange='        dynamicLearningR   = ['${learningRate[j]}','${learningRate[j]}'];'

                #Change values in the config file
	        sed -i.bu '23 s|.*|'"$varLearning"'|' ./config/config.cfg
                sed -i.bu '24 s|.*|'"$varLearningRange"'|' ./config/config.cfg

                #Iterate through hidden layers
                for i in `seq 0 1 $[${#lambdaArray[@]}-1]`
                do
                        #Set the path to a new directory
                        saveDir="/local/data/public/am2442/seismic/output/results/contractive/sigm/${batch[k]}/${learningRate[j]}/${lambdaArray[i]}"

                        #Create a new directory for output      
                        mkdir -p $saveDir

                        #Set a new value for lambda
                        varold='        lambda             = '${lambdaArray[i]}';'

                        #Change a save folder to a created directory
                        varoldSave='        saveFolder         ="'$saveDir'/";'

                        #Set new variables in the config file
	                sed -i.bu '35 s|.*|'"$varold"'|' ./config/config.cfg
	                sed -i.bu '4 s|.*|'"$varoldSave"'|' ./config/config.cfg

                        #Run the neural network with a new configuration file
	                make run
                done
        done
done

