#!/bin/bash

#Script to merge the time infomation from the time.dat folder

for d in ../../output/*/ ; do

    timepath=$d'time.dat'

    timetaken=$(sed '1!d' $timepath)
    
    linetoprint=$timetaken' '$numberlayers

    echo $linetoprint >>../../output/datafile.txt


done


