#!/bin/bash

# Script to run through the maxVal sizes (alters config file and runs the algorithm)


#Go to the head folder with a Makefile in it
cd ../../

#Declaring arrays of the parameters we want to test
#declare -a penalty=(128)
declare -a penalty=(0.001)
declare -a maxVal=(0.005 0.01 0.05)
declare -a learningRate=(0.1)
folderToSave="/local/data/public/am2442/seismic/output/results/sparseRegTR2/sigm"
#declare -a maxVal=(4 16 64)


#Iterate through maxVal array
        for k in `seq 0 1 $[${#maxVal[@]}-1]`
        do      
                #Set a new value for maxVal variable in config
                varmaxVal='        sparcityParameter = '${maxVal[k]}';'

                #Change a maxVal variable in the config
                sed -i.bu '28 s|.*|'"$varmaxVal"'|' ./config/config.cfg


                #Iterate through learning rate array
                for j in `seq 0 1 $[${#learningRate[@]}-1]`
                do
                        #Set a new value for Learning rate variables
                        varLearning='        learningRate       = '${learningRate[j]}';'
                        varLearningRange='        dynamicLearningR   = ['${learningRate[j]}','${learningRate[j]}'];'

                        #Change values in the config file
	                sed -i.bu '23 s|.*|'"$varLearning"'|' ./config/config.cfg
                        sed -i.bu '24 s|.*|'"$varLearningRange"'|' ./config/config.cfg

                        #Iterate through hidden layers
                        for i in `seq 0 1 $[${#penalty[@]}-1]`
                        do
                                #Set the path to a new directory
                                saveDir="$folderToSave/${maxVal[k]}/${learningRate[j]}/${penalty[i]}"

                                #Create a new directory for output      
                                mkdir -p $saveDir

                                #Set a new value for the hidden layers output
                                #varold='        layers             = [64, '${penalty[i]}', 64];'
                                varold='        sparse             = '${penalty[i]}';'

                                #Change a save folder to a created directory
                                varoldSave='        saveFolder         ="'$saveDir'/";'

                                #Set new variables in the config file
	                        sed -i.bu '29 s|.*|'"$varold"'|' ./config/config.cfg
	                        sed -i.bu '4 s|.*|'"$varoldSave"'|' ./config/config.cfg

                                #Run the neural network with a new configuration file
	                        make run
                        done
                done
        done

